name: Deploy lambda get-logs-func

# Trigger deployment only on push to main branch
on:
  push:
    branches:
      - main

jobs:
  build:
    name: Deploy lambda
    runs-on: ubuntu-latest
    permissions: write-all
    env: 
      RUN_NUMBER: ${{ github.run_number }}
    steps:
      - name: Login to Vultr Instance and deploy lambda
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VULTR_INSTANCE_IP }}
          username: ${{ secrets.VULTR_INSTANCE_USER }}
          key: ${{ secrets.VULTR_INSTANCE_KEY }}
          script: |
            cd cloudwatch-mock
            [ -e get-logs-func.zip ] && rm get-logs-func.zip
            [ -e get_logs_func.zip ] && rm get_logs_func.zip
            git pull
            git stash
            curl -L -o get-logs-func.zip https://github.com/TudorIonutElian/get-logs-func/archive/refs/heads/main.zip
            unzip get-logs-func.zip -d get-logs-func

            mv get-logs-func/get-logs-func-main/* get-logs-func/
            rm -r get-logs-func/get-logs-func-main
            rm get-logs-func.zip

            cd get-logs-func
            npm install
            ls -la
            zip -r get_logs_func.zip . -x "*.github*"
            aws lambda update-function-code --function-name get-logs-func --zip-file fileb://get_logs_func.zip
            